### ISSUE TITLE
Tracking: Ideas for useful helper functions

### ISSUE THREAD

**Issue by matheus23** [earthstar-project/willow-rs#56]
I'll try keeping track of some useful helper functions to include in `willow-rs`.

- [ ] Some form of `Range::new_exact`:
  ```rs
  impl Range<Path> {
    fn new_exact_path(path: Path) -> Self;
  }
  ```
  
  An alternative for this would be:
  ```rs
  trait Successor { // which is actually equivalent to `trait SubspaceId` at this point.
    fn successor(&self) -> Option<Self>;
  }
  
  impl<T: Successor> Range<T> {
    fn new_exact(value: T) -> Self;
  }
  ```
- [ ] Helpers for creating `Path`s from arrays of bytes/strings:
  ```rs
  impl Path {
    fn from_bytes(&[&[u8]]) -> Self;
    fn from_strs(&[&str]) -> Self;
  }
  ```
- [ ] Helpers for printing `Path`s. Perhaps just a nice `Path: Debug` instance that interprets the path segments as utf8, if possible, or otherwise escapes to hex or similar. Alternatively something like `Path::to_string(&self) -> Option<String>` that tries to format using `/` and utf8, but fails if the path would have to be escaped.
- [ ] Easily converting an `Area` into a `Range3d`: `Area::to_range3d(&self) -> Range3d`. Alternatively: a `From`/`Into` instance.
- [ ] Easily converting an `Area` into an `AreaOfInterest`: `AreaOfInterest::new_area(area: Area) -> Self` or similar

**Comment by sgwilym** [comment]
Thank you for these suggestions, I'm agreed on all counts. I like the `Successor` trait, I think the only drawback would be needing a newtype to implement it on `u64` for timestamps.

**Comment by matheus23** [comment]
FWIW, I personally find it *just* easy enough to do a `Range::new_closed`, if it's a `Range<u64>`, so I'd be fine without a newtype.
